### ISSUE TITLE
Doubled hostname variable in flake-deployed liberaforms instances

### ISSUE THREAD

**Issue by cleeyv** [ngi-nix/liberaforms#3]
On August 28th I started testing of a liberaforms instance and I ran into an issue in which a doubled version of the "hostname" variable that LiberaForms uses internally is generated at the initialization of the app. 

For example, if the address I initially visit the app through with a browser is "10.233.1.2" then the internal hostname will be configured (stored in the database) as "10.233.1.2,10.233.1.2" this breaks various URLs generated by the interface, though this can be worked around by removing the extra address from the URL each time it happens. 

I dug around in the LiberaForms code to try to figure out a cause but haven't found anything conclusive yet. Fortunately, the liberaforms devs are interested in packaging for nix, and already have a nixos machine ready to test it out on. At their request, I wrote [preliminary docs](https://github.com/ngi-nix/liberaforms/blob/flake/docs/nixos.md) for them to use for testing. 

On August 31st, I heard back from the dev I was in contact with:

> I've just finished following your documentation. First time success!
>    > I initially visit the app through with a browser is "10.233.1.2" then the internal hostname will be configured (stored in the database) as "10.233.1.2,10.233.1.2" this breaks various URLs generated by the interface,
>
>    Yep. I see this too. First time I've come across this problem. I'll look into it!

I'm creating this issue for now while the work on flakes is happening here. However, the liberaforms devs are using [Gitlab](https://gitlab.com/groups/liberaforms/-/issues) so it may make sense to move this issue to there at some point.

**Comment by buttle** [comment]
Hi!

I've been trying to trouble-shoot this but without much luck. I can confirm that it does not happen on a new non-nix installation.

I was thinking if it might be because the nginx config defines the server_name as liberaforms.local but recreating the container and browsing to http://liberaforms.local (adjusting my /etc/hosts accordingly) does not help. same problem.

I thought to bypass nginx all together to rule out an ngnix config issue and access the site via http://liberaforms.local:5000. So I set gunicorn to listing on `0.0.0.0` and did

```
iptables -t nat -A PREROUTING -p tcp --dport 5000 -j DNAT --to-destination 10.233.1.2:5000
iptables -t nat -A POSTROUTING -j MASQUERADE
```
And inside the container
```
iptables -I nixos-fw 3 -p tcp --dport 5000 -j nixos-fw-accept
```
Then I browse to the new installation in the container at `http://liberaforms.local:5000` and check the database with

```
select hostname from site where 1=1;
     hostname      
-------------------
 liberaforms.local
(1 row)
```
It works!

It seems there is something happening with nginx config but I have not been able to discover it.

**Comment by cleeyv** [comment]
Once you had narrowed it down to likely being an nginx configuration issue, it didn't take long for me to see the problem: a repeated line in the nginx proxy config that was resulting in a double hostname in the http headers. This commit seems to have fixed it: https://github.com/ngi-nix/liberaforms/commit/fec22a66e7caa34db9f9a4519e955ec8948d0b10 
Thank you for your help with this!
